# 0927

## - relu

In [1]:
import numpy as np
def relu(x):
    return np.maximum(0,x)

relu([-1,1])

array([0, 1])

## - 내적

In [2]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [5]:
B = np.array([[1,2],
             [3,4],
             [5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.ndim(B)

2

In [7]:
B.shape

(3, 2)

In [8]:
A = np.array([[1,2],
             [3,4]])
A.shape

(2, 2)

In [9]:
B = np.array([[5,6],
              [7,8]])
B.shape

(2, 2)

In [10]:
A@B

array([[19, 22],
       [43, 50]])

In [11]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array(range(1,97)).reshape(3,4,2,4)
B = np.array(range(1,97)).reshape(4,2,4,3)
a = np.dot(A,B)
a.shape

(3, 4, 2, 4, 2, 3)

In [13]:
A = np.arange(60).reshape(2,3,10)
B = np.arange(60).reshape(3,10,2)
np.dot(A,B).shape

(2, 3, 3, 2)

In [14]:
A = np.arange(60).reshape(4,3,1,5)
B = np.arange(60).reshape(3,1,5,4)
np.dot(A,B).shape

(4, 3, 1, 3, 1, 4)

In [15]:
# a.shape = (1,2,3,4,5,6,7,8), b.shape = (1,1,1,1,1,1,8,1) 이면 내적 가능
# a@b 일때, a[-1] == b[-2] 여야 내적이 가능하다.
A = np.arange(1*2*3*4*5*6*7*8).reshape(1,2,3,4,5,6,7,8)
B = np.arange(8).reshape(1,1,1,1,1,1,8,1)
np.dot(A,B).shape

(1, 2, 3, 4, 5, 6, 7, 1, 1, 1, 1, 1, 1, 1)

In [16]:
A = np.arange(1*2*3*4).reshape(1,2,3,4)
B = np.arange(1*2*3*4).reshape(1,2,4,3)
C = np.arange(1*2*3*4).reshape(1,4,3,2)
# 1,2,3 -> A, 1,2 -> B, 1,4,2 -> C
A.dot(B).dot(C).shape

(1, 2, 3, 1, 2, 1, 4, 2)

In [17]:
A = np.arange(1*2*3*4).reshape(1,2,3,4)
B = np.arange(1*2*3*4).reshape(1,2,4,3)
C = np.arange(1*2*3*4).reshape(1,4,3,2)
D = np.arange(1*2*3*4).reshape(4,3,2,1)
# 1,2,3 -> A, 1,2 -> B, 1,4 -> C, 4,3,1 -> D
A.dot(B).dot(C).dot(D).shape

(1, 2, 3, 1, 2, 1, 4, 4, 3, 1)

In [18]:
w = np.arange(6).reshape(2,3)
x = np.arange(2).reshape(1,2)
x@w

array([[3, 4, 5]])

In [19]:
w.T@x.T

array([[3],
       [4],
       [5]])

## - 신경망

In [20]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],
              [0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
A1

(2, 3)
(2,)
(3,)


array([0.3, 0.7, 1.1])

In [21]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [22]:
Z1 = sigmoid(A1)
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [23]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

(3,)
(3, 2)
(2,)


array([0.62624937, 0.7710107 ])

In [24]:
def identity_function(x):
    return x

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])

In [25]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


## - 소프트맥스

In [26]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


## - MNIST 데이터셋

In [27]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [28]:
(x_train, t_train), (x_test, t_test) = \
    load_mnist(flatten=True, normalize=False)

In [29]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [30]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image

def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

(x_train, t_train), (x_test, t_test) = \
    load_mnist(flatten=True, normalize=False)

img = x_train[0]
label = t_train[0]
print(label)

print(img.shape)
img = img.reshape(28,28)
print(img.shape)

img_show(img)

5
(784,)
(28, 28)


In [31]:
import pickle
def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(flatten=True, normalize=True, one_hot_label=False)
    return x_test, t_test

def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
        
    return network

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y

In [32]:
x, t = get_data()
network = init_network()

accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
    
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


In [33]:
x, _ = get_data()
network = init_network()
W1, W2, W3 = network['W1'], network['W2'], network['W3']
x.shape

(10000, 784)

In [34]:
W1.shape

(784, 50)

In [35]:
W2.shape

(50, 100)

In [36]:
W3.shape

(100, 10)

In [37]:
x, t = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network,x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


In [38]:
p

array([8, 9, 0, 1, 2, 9, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 7, 8, 9, 7, 8, 6,
       4, 1, 9, 2, 8, 4, 4, 7, 0, 1, 9, 2, 8, 7, 8, 2, 6, 0, 0, 6, 3, 5,
       9, 9, 1, 4, 0, 6, 1, 0, 0, 6, 2, 1, 1, 7, 7, 8, 4, 6, 0, 7, 0, 3,
       6, 8, 7, 1, 3, 2, 4, 9, 4, 3, 6, 4, 1, 7, 2, 6, 2, 0, 1, 2, 8, 4,
       5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6], dtype=int64)